### PR TITLE
Merge with xhochy

### PR DESCRIPTION
**Pull request by marc9595**
I dropped all of our commits and I am using this branch to test the code of `xhochy/fletcher` in our code.

### CODE REVIEW

**Comment by marc9595** [comment]
All of our fix have been merged in `xhochy/fletcher` (except for https://github.com/tinyclues/fletcher/commit/77d8014ce5219dc0e4d874f6023fb91987fae23c but it won't appear when using `FletcherContinuousArray`). We can now work with `xhochy/fletcher`.
There are some helpers to write in our code, the PRs where I propagated this version of `fletcher` are: https://github.com/tinyclues/predictive-services-io/pull/117, https://github.com/tinyclues/predictive-services-model/pull/380, https://github.com/tinyclues/predictive-services-pipeline/pull/539

**Comment by artemru** [comment]
rebase is needed, no?

**Comment by artemru** [comment]
(: it hard to review all 6K lines, do you want us to be focused to some particular commits ?

**Comment by marc9595** [comment]
Rebase seems pretty much impossible, this [PR](https://github.com/tinyclues/fletcher/pull/54) is clearer

**Pull request closed without merging**
